const arregloTagsCamaronEB = () => {
    return arreglo = `["Camaron_FCAM_EBG1_St1_Corriente_L1","Camaron_FCAM_EBG1_St1_Corriente_L2","Camaron_FCAM_EBG1_St1_Corriente_L3","Camaron_FCAM_EBG1_St1_Energ_Activa","Camaron_FCAM_EBG1_St1_Factor_Potencia","Camaron_FCAM_EBG1_St1_Group_Alarm1","Camaron_FCAM_EBG1_St1_Group_Alarm2","Camaron_FCAM_EBG1_St1_Group_Alarm3","Camaron_FCAM_EBG1_St1_Horometro","Camaron_FCAM_EBG1_St1_Hrs_Dia","Camaron_FCAM_EBG1_St1_Hrs_Dia_Ant","Camaron_FCAM_EBG1_St1_Potencia_Activa","Camaron_FCAM_EBG1_St1_Status","Camaron_FCAM_EBG1_St1_Tens_red_U_L1-L2","Camaron_FCAM_EBG1_St1_Tens_red_U_L2-L3","Camaron_FCAM_EBG1_St1_Tens_red_U_L3-L1","Camaron_FCAM_EBG1_St2_Corriente_L1","Camaron_FCAM_EBG1_St2_Corriente_L2","Camaron_FCAM_EBG1_St2_Corriente_L3","Camaron_FCAM_EBG1_St2_Energ_Activa","Camaron_FCAM_EBG1_St2_Factor_Potencia","Camaron_FCAM_EBG1_St2_Group_Alarm1","Camaron_FCAM_EBG1_St2_Group_Alarm2","Camaron_FCAM_EBG1_St2_Group_Alarm3","Camaron_FCAM_EBG1_St2_Horometro","Camaron_FCAM_EBG1_St2_Hrs_Dia","Camaron_FCAM_EBG1_St2_Hrs_Dia_Ant","Camaron_FCAM_EBG1_St2_Potencia_Activa","Camaron_FCAM_EBG1_St2_Status","Camaron_FCAM_EBG1_St2_Tens_red_U_L1-L2","Camaron_FCAM_EBG1_St2_Tens_red_U_L2-L3","Camaron_FCAM_EBG1_St2_Tens_red_U_L3-L1","Camaron_FCAM_EBG1_St3_Corriente_L1","Camaron_FCAM_EBG1_St3_Corriente_L2","Camaron_FCAM_EBG1_St3_Corriente_L3","Camaron_FCAM_EBG1_St3_Energ_Activa","Camaron_FCAM_EBG1_St3_Factor_Potencia","Camaron_FCAM_EBG1_St3_Group_Alarm1","Camaron_FCAM_EBG1_St3_Group_Alarm2","Camaron_FCAM_EBG1_St3_Group_Alarm3","Camaron_FCAM_EBG1_St3_Horometro","Camaron_FCAM_EBG1_St3_Hrs_Dia","Camaron_FCAM_EBG1_St3_Hrs_Dia_Ant","Camaron_FCAM_EBG1_St3_Potencia_Activa","Camaron_FCAM_EBG1_St3_Status","Camaron_FCAM_EBG1_St3_Tens_red_U_L1-L2","Camaron_FCAM_EBG1_St3_Tens_red_U_L2-L3","Camaron_FCAM_EBG1_St3_Tens_red_U_L3-L1","Camaron_FCAM_EBG2_St1_Corriente_L1","Camaron_FCAM_EBG2_St1_Corriente_L2","Camaron_FCAM_EBG2_St1_Corriente_L3","Camaron_FCAM_EBG2_St1_Energ_Activa","Camaron_FCAM_EBG2_St1_Factor_Potencia","Camaron_FCAM_EBG2_St1_Group_Alarm1","Camaron_FCAM_EBG2_St1_Group_Alarm2","Camaron_FCAM_EBG2_St1_Group_Alarm3","Camaron_FCAM_EBG2_St1_Horometro","Camaron_FCAM_EBG2_St1_Hrs_Dia","Camaron_FCAM_EBG2_St1_Hrs_Dia_Ant","Camaron_FCAM_EBG2_St1_Potencia_Activa","Camaron_FCAM_EBG2_St1_Status","Camaron_FCAM_EBG2_St1_Tens_red_U_L1-L2","Camaron_FCAM_EBG2_St1_Tens_red_U_L2-L3","Camaron_FCAM_EBG2_St1_Tens_red_U_L3-L1","Camaron_FCAM_EBG2_St2_Corriente_L1","Camaron_FCAM_EBG2_St2_Corriente_L2","Camaron_FCAM_EBG2_St2_Corriente_L3","Camaron_FCAM_EBG2_St2_Energ_Activa","Camaron_FCAM_EBG2_St2_Factor_Potencia","Camaron_FCAM_EBG2_St2_Group_Alarm1","Camaron_FCAM_EBG2_St2_Group_Alarm2","Camaron_FCAM_EBG2_St2_Group_Alarm3","Camaron_FCAM_EBG2_St2_Horometro","Camaron_FCAM_EBG2_St2_Hrs_Dia","Camaron_FCAM_EBG2_St2_Hrs_Dia_Ant","Camaron_FCAM_EBG2_St2_Potencia_Activa","Camaron_FCAM_EBG2_St2_Status","Camaron_FCAM_EBG2_St2_Tens_red_U_L1-L2","Camaron_FCAM_EBG2_St2_Tens_red_U_L2-L3","Camaron_FCAM_EBG2_St2_Tens_red_U_L3-L1"]`
};

const arregloTagsCamaronEBGeneral = () => {
    return arreglo = `["Camaron_FCAM_EBG1_Hora_Bomb_Fin_1","Camaron_FCAM_EBG1_Hora_Bomb_Fin_2","Camaron_FCAM_EBG1_Hora_Bomb_Ini_1","Camaron_FCAM_EBG1_Hora_Bomb_Ini_2","Camaron_FCAM_EBG1_Inputs_Plc","Camaron_FCAM_EBG1_Niv_Desc","Camaron_FCAM_EBG1_Niv_Succ","Camaron_FCAM_EBG1_Outputs","Camaron_FCAM_EBG1_Stp_Niv_Desc","Camaron_FCAM_EBG1_Stp_Niv_Succ_1","Camaron_FCAM_EBG1_Stp_Niv_Succ_2","Camaron_FCAM_EBG1_Stp_Niv_Succ_3","Camaron_FCAM_EBG2_Hora_Bomb_Fin_1","Camaron_FCAM_EBG2_Hora_Bomb_Fin_2","Camaron_FCAM_EBG2_Hora_Bomb_Ini_1","Camaron_FCAM_EBG2_Hora_Bomb_Ini_2","Camaron_FCAM_EBG2_Inputs_Plc","Camaron_FCAM_EBG2_Niv_Desc","Camaron_FCAM_EBG2_Niv_Succ","Camaron_FCAM_EBG2_Outputs","Camaron_FCAM_EBG2_Stp_Niv_Desc","Camaron_FCAM_EBG2_Stp_Niv_Succ_1","Camaron_FCAM_EBG2_Stp_Niv_Succ_2"]`
};

const arregloTagsCamaronEBTCP = () => {
    return arreglo = `["Camaron_FCAM_EBG1_TCP_Alarm1","Camaron_FCAM_EBG1_TCP_Alarm2","Camaron_FCAM_EBG1_TCP_I_1","Camaron_FCAM_EBG1_TCP_I_2","Camaron_FCAM_EBG1_TCP_I_3","Camaron_FCAM_EBG1_TCP_I_Tot","Camaron_FCAM_EBG1_TCP_P_Total","Camaron_FCAM_EBG1_TCP_Pasos_Acti","Camaron_FCAM_EBG1_TCP_Pasos_Habilit","Camaron_FCAM_EBG1_TCP_PF_Avg","Camaron_FCAM_EBG1_TCP_T1_Imp_Act_Index","Camaron_FCAM_EBG1_TCP_T1_Imp_Act_Month","Camaron_FCAM_EBG1_TCP_THDI_tot","Camaron_FCAM_EBG1_TCP_THDV_tot","Camaron_FCAM_EBG1_TCP_V_1","Camaron_FCAM_EBG1_TCP_V_12","Camaron_FCAM_EBG1_TCP_V_2","Camaron_FCAM_EBG1_TCP_V_23","Camaron_FCAM_EBG1_TCP_V_3","Camaron_FCAM_EBG1_TCP_V_31","Camaron_FCAM_EBG1_TCP_V_Avg","Camaron_FCAM_EBG1_TCP_VLL_Avg","Camaron_FCAM_EBG2_TCP_Alarm1","Camaron_FCAM_EBG2_TCP_Alarm2","Camaron_FCAM_EBG2_TCP_I_1","Camaron_FCAM_EBG2_TCP_I_2","Camaron_FCAM_EBG2_TCP_I_3","Camaron_FCAM_EBG2_TCP_I_Tot","Camaron_FCAM_EBG2_TCP_P_Total","Camaron_FCAM_EBG2_TCP_Pasos_Acti","Camaron_FCAM_EBG2_TCP_Pasos_Habilit","Camaron_FCAM_EBG2_TCP_PF_Avg","Camaron_FCAM_EBG2_TCP_T1_Imp_Act_Index","Camaron_FCAM_EBG2_TCP_T1_Imp_Act_Month","Camaron_FCAM_EBG2_TCP_THDI_tot","Camaron_FCAM_EBG2_TCP_THDV_tot","Camaron_FCAM_EBG2_TCP_V_1","Camaron_FCAM_EBG2_TCP_V_12","Camaron_FCAM_EBG2_TCP_V_2","Camaron_FCAM_EBG2_TCP_V_23","Camaron_FCAM_EBG2_TCP_V_3","Camaron_FCAM_EBG2_TCP_V_31","Camaron_FCAM_EBG2_TCP_V_Avg","Camaron_FCAM_EBG2_TCP_VLL_Avg"]`
};

const arregloTagsCamaronEBAntenas = () => {
    return arreglo = `["Camaron_CAM_Ant_Pot_EB_CAM","Camaron_CAM_Ant_Stat_EB_CAM","Camaron_CAM_Ant_Pot_AP_EB_CAM","Camaron_CAM_Ant_Stat_AP_EB_CAM","Camaron_CAM_Ant_Pot_PTP_TORRE_CAM","Camaron_CAM_Ant_Stat_PTP_TORRE_CAM","Camaron_CAM_Ant_Pot_AP_CAM","Camaron_CAM_Ant_Stat_AP_CAM"]`
};



module.exports = {
    arregloTagsCamaronEB,
    arregloTagsCamaronEBGeneral,
    arregloTagsCamaronEBTCP,
    arregloTagsCamaronEBAntenas,
}

